language: go
go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
install:
  - go get github.com/bmizerany/assert
  - go get github.com/ugorji/go/codec
matrix:
  allow_failures:
    - go: 1.0
    - go: 1.1
    - go: tip